version: '3.8'
services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: catalog-service
    container_name: catalog-service
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polar_catalog
      - SPRING_DATASOURCE_USERNAME=polar
      - SPRING_DATASOURCE_PASSWORD=polar
      - SPRING_PROFILES_ACTIVE=testdata
  polar-postgres:
    image: postgres:15-alpine
    container_name: polar-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=polar
      - POSTGRES_PASSWORD=polar
      - POSTGRES_DB=polar_catalog
